/* Golden-image tests for the spatial filters in libim_process.
 *
 * Every other test in this suite checks IM against hand-computed values or
 * against IM itself. Neither catches an operation that is self-consistently
 * wrong -- a median filter that took the wrong element of the sorted window
 * would round-trip, forward correctly through the C++ wrapper, and satisfy
 * every structural assertion written about it. Only a second implementation
 * catches that, which is what the fixtures in fixtures/golden/ are: outputs
 * produced by ImageMagick 7, regenerated by the script beside them.
 *
 * How closely the two agree is not uniform, and the cases below say which
 * they are relying on rather than applying one blanket tolerance:
 *
 *   minimum, maximum, open, close, range   exact over the whole image
 *   median 3x3 and 5x5                     exact in the interior only
 *   mean 3x3                               within 1
 *
 * The borders are where a median disagrees because the two libraries pad the
 * window differently past the edge -- a genuine ambiguity in the operation,
 * not a defect in either -- so those cases compare the interior and say so.
 * That min and max agree everywhere, borders included, is worth more than it
 * looks: it means the two libraries also pad identically, so the median
 * difference really is confined to how the sorted window is filled.
 */

#include "doctest/doctest.h"

#include <im.h>
#include <im_util.h>
#include <im_image.h>
#include <im_process.h>

#include <stdio.h>
#include <string.h>
#include <string>

namespace {

std::string golden(const char* name)
{
  return std::string(IM_TEST_FIXTURE_DIR) + "/golden/" + name;
}

imImage* load_golden(const char* name)
{
  int error = IM_ERR_NONE;
  imImage* image = imFileImageLoad(golden(name).c_str(), 0, &error);
  REQUIRE_MESSAGE(image != NULL,
                  "could not load " << std::string(name) << ", error " << error);
  return image;
}

/* Compares every sample at least `margin` pixels in from each edge. A margin
   of zero compares the whole image. Returns the worst absolute difference. */
int worst_difference(const imImage* a, const imImage* b, int margin)
{
  REQUIRE(a->width == b->width);
  REQUIRE(a->height == b->height);

  int worst = 0;
  for (int y = margin; y < a->height - margin; y++)
  {
    for (int x = margin; x < a->width - margin; x++)
    {
      int i = y * a->width + x;
      int diff = (int)((imbyte*)a->data[0])[i] - (int)((imbyte*)b->data[0])[i];
      if (diff < 0) diff = -diff;
      if (diff > worst) worst = diff;
    }
  }
  return worst;
}

/* A filter that returned its input unchanged, or a constant, would satisfy a
   "close enough to the reference" assertion if the reference happened to be
   close to the input. It is not, on this source -- but assert it rather than
   assume it. */
void check_actually_filtered(const imImage* result, const imImage* source)
{
  int differing = 0;
  int distinct = 0;
  imbyte first = ((imbyte*)result->data[0])[0];
  for (int i = 0; i < result->count; i++)
  {
    if (((imbyte*)result->data[0])[i] != ((imbyte*)source->data[0])[i])
      differing++;
    if (((imbyte*)result->data[0])[i] != first)
      distinct = 1;
  }
  CHECK(differing > result->count / 10);   /* it did something */
  CHECK(distinct == 1);                    /* and not by flattening the image */
}

} /* namespace */


TEST_CASE("golden: the source fixture is what the reference was made from")
{
  /* If this drifts, every case below is comparing against outputs for a
     different input and the agreement they assert is meaningless. */
  imImage* src = load_golden("src.pgm");

  CHECK(src->width == 32);
  CHECK(src->height == 24);
  CHECK(src->data_type == IM_BYTE);
  CHECK(imColorModeSpace(src->color_space) == IM_GRAY);

  /* Counted with ImageMagick's own histogram when the fixtures were made:
     "magick src.pgm -format %c histogram:info:-". */
  unsigned long histogram[256];
  REQUIRE(imCalcGrayHistogram(src, histogram, 0) != 0);

  CHECK(histogram[0] == 8);
  CHECK(histogram[1] == 7);
  CHECK(histogram[4] == 6);
  CHECK(histogram[7] == 6);
  CHECK(histogram[10] == 3);
  CHECK(histogram[12] == 1);

  unsigned long total = 0;
  for (int i = 0; i < 256; i++)
    total += histogram[i];
  CHECK(total == 32 * 24);

  imImageDestroy(src);
}

TEST_CASE("golden: image statistics agree with an independent measurement")
{
  /* ImageMagick reported, on the same file and scaled from its Q16 range:
     mean 129.09, min 0, max 255, standard deviation 65.19. */
  imImage* src = load_golden("src.pgm");

  imStats stats;
  REQUIRE(imCalcImageStatistics(src, &stats) != 0);

  CHECK(stats.min == doctest::Approx(0.0));
  CHECK(stats.max == doctest::Approx(255.0));
  CHECK(stats.mean == doctest::Approx(129.09).epsilon(0.001));
  CHECK(stats.stddev == doctest::Approx(65.19).epsilon(0.01));

  imImageDestroy(src);
}

TEST_CASE("golden: the minimum and maximum filters match exactly, borders included")
{
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  REQUIRE(dst != NULL);

  SUBCASE("RankMinConvolve")
  {
    imImage* want = load_golden("min3.pgm");
    REQUIRE(imProcessRankMinConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("RankMaxConvolve")
  {
    imImage* want = load_golden("max3.pgm");
    REQUIRE(imProcessRankMaxConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("RangeConvolve is the difference of the two")
  {
    imImage* want = load_golden("range3.pgm");
    REQUIRE(imProcessRangeConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    imImageDestroy(want);
  }

  imImageDestroy(src);
  imImageDestroy(dst);
}

TEST_CASE("golden: gray morphology is the same pair of filters")
{
  /* Erode and dilate over a square structuring element are the minimum and
     maximum filters, so they are held to the same references -- which also
     pins the two families to each other. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  REQUIRE(dst != NULL);

  SUBCASE("Erode is the minimum filter")
  {
    imImage* want = load_golden("min3.pgm");
    REQUIRE(imProcessGrayMorphErode(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    imImageDestroy(want);
  }
  SUBCASE("Dilate is the maximum filter")
  {
    imImage* want = load_golden("max3.pgm");
    REQUIRE(imProcessGrayMorphDilate(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    imImageDestroy(want);
  }
  SUBCASE("Open is an erode followed by a dilate")
  {
    imImage* want = load_golden("open3.pgm");
    REQUIRE(imProcessGrayMorphOpen(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("Close is the other order")
  {
    imImage* want = load_golden("close3.pgm");
    REQUIRE(imProcessGrayMorphClose(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);

    /* Opening and closing are different operations; a build where one was
       wired to the other would pass each of the two cases above only if they
       compared against the same reference, so check they diverge. */
    imImage* opened = imImageCreateBased(src, -1, -1, -1, -1);
    REQUIRE(imProcessGrayMorphOpen(src, opened, 3) != 0);
    CHECK(worst_difference(dst, opened, 0) > 0);
    imImageDestroy(opened);

    imImageDestroy(want);
  }

  imImageDestroy(src);
  imImageDestroy(dst);
}

TEST_CASE("golden: the median filter matches exactly away from the border")
{
  /* The border is where the two libraries legitimately differ: the window
     runs off the edge and they fill it differently. Everything further in
     than half the kernel is unambiguous, and matches to the sample. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  REQUIRE(dst != NULL);

  SUBCASE("3x3")
  {
    imImage* want = load_golden("median3.pgm");
    REQUIRE(imProcessMedianConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 1) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("5x5")
  {
    /* A larger window, so a bug in how the window is gathered rather than
       sorted has somewhere to show. */
    imImage* want = load_golden("median5.pgm");
    REQUIRE(imProcessMedianConvolve(src, dst, 5) != 0);
    CHECK(worst_difference(dst, want, 2) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }

  SUBCASE("and it is not simply the minimum or the maximum")
  {
    /* The three rank filters share their window-gathering code, so a median
       that returned the wrong element of the sorted window would still agree
       with itself everywhere. */
    imImage* median = imImageCreateBased(src, -1, -1, -1, -1);
    imImage* other = imImageCreateBased(src, -1, -1, -1, -1);
    REQUIRE(imProcessMedianConvolve(src, median, 3) != 0);

    REQUIRE(imProcessRankMinConvolve(src, other, 3) != 0);
    CHECK(worst_difference(median, other, 1) > 0);

    REQUIRE(imProcessRankMaxConvolve(src, other, 3) != 0);
    CHECK(worst_difference(median, other, 1) > 0);

    imImageDestroy(median);
    imImageDestroy(other);
  }

  imImageDestroy(src);
  imImageDestroy(dst);
}

TEST_CASE("golden: the mean filter matches within the rounding difference")
{
  /* The only one of these that is not exact. Both libraries average the same
     nine samples; they disagree only on how the average is rounded back to a
     byte, which is at most one. A bound of 1 still fails on anything
     structural -- a shifted window or a wrong divisor moves samples by tens. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  imImage* want = load_golden("mean3.pgm");
  REQUIRE(dst != NULL);

  REQUIRE(imProcessMeanConvolve(src, dst, 3) != 0);
  CHECK(worst_difference(dst, want, 1) <= 1);
  check_actually_filtered(dst, src);

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}
