/* Golden-image tests for the spatial filters in libim_process.
 *
 * Every other test in this suite checks IM against hand-computed values or
 * against IM itself. Neither catches an operation that is self-consistently
 * wrong -- a median filter that took the wrong element of the sorted window
 * would round-trip, forward correctly through the C++ wrapper, and satisfy
 * every structural assertion written about it. Only a second implementation
 * catches that, which is what the fixtures in fixtures/golden/ are: outputs
 * produced by ImageMagick 7, regenerated by the script beside them.
 *
 * How closely the two agree is not uniform, and the cases below say which
 * they are relying on rather than applying one blanket tolerance:
 *
 *   minimum, maximum, open, close, range,  exact over the whole image
 *   binary dilate, 2x nearest resize,
 *   Otsu threshold
 *   median 3x3 and 5x5, binary erode       exact in the interior only
 *   mean 3x3, RGB to gray                  within 1
 *
 * The borders are where a median disagrees because the two libraries pad the
 * window differently past the edge -- a genuine ambiguity in the operation,
 * not a defect in either -- so those cases compare the interior and say so.
 * That min and max agree everywhere, borders included, is worth more than it
 * looks: it means the two libraries also pad identically, so the median
 * difference really is confined to how the sorted window is filled.
 */

#include "doctest/doctest.h"

#include <im.h>
#include <im_util.h>
#include <im_image.h>
#include <im_process.h>
#include <im_convert.h>

#include <stdio.h>
#include <string.h>
#include <string>

namespace {

std::string golden(const char* name)
{
  return std::string(IM_TEST_FIXTURE_DIR) + "/golden/" + name;
}

imImage* load_golden(const char* name)
{
  int error = IM_ERR_NONE;
  imImage* image = imFileImageLoad(golden(name).c_str(), 0, &error);
  REQUIRE_MESSAGE(image != NULL,
                  "could not load " << std::string(name) << ", error " << error);
  return image;
}

/* Compares every sample at least `margin` pixels in from each edge. A margin
   of zero compares the whole image. Returns the worst absolute difference. */
int worst_difference(const imImage* a, const imImage* b, int margin)
{
  REQUIRE(a->width == b->width);
  REQUIRE(a->height == b->height);

  int worst = 0;
  for (int y = margin; y < a->height - margin; y++)
  {
    for (int x = margin; x < a->width - margin; x++)
    {
      int i = y * a->width + x;
      int diff = (int)((imbyte*)a->data[0])[i] - (int)((imbyte*)b->data[0])[i];
      if (diff < 0) diff = -diff;
      if (diff > worst) worst = diff;
    }
  }
  return worst;
}

/* A filter that returned its input unchanged, or a constant, would satisfy a
   "close enough to the reference" assertion if the reference happened to be
   close to the input. It is not, on this source -- but assert it rather than
   assume it. */
void check_actually_filtered(const imImage* result, const imImage* source)
{
  int differing = 0;
  int distinct = 0;
  imbyte first = ((imbyte*)result->data[0])[0];
  for (int i = 0; i < result->count; i++)
  {
    if (((imbyte*)result->data[0])[i] != ((imbyte*)source->data[0])[i])
      differing++;
    if (((imbyte*)result->data[0])[i] != first)
      distinct = 1;
  }
  CHECK(differing > result->count / 10);   /* it did something */
  CHECK(distinct == 1);                    /* and not by flattening the image */
}

} /* namespace */


TEST_CASE("golden: the source fixture is what the reference was made from")
{
  /* If this drifts, every case below is comparing against outputs for a
     different input and the agreement they assert is meaningless. */
  imImage* src = load_golden("src.pgm");

  CHECK(src->width == 32);
  CHECK(src->height == 24);
  CHECK(src->data_type == IM_BYTE);
  CHECK(imColorModeSpace(src->color_space) == IM_GRAY);

  /* Counted with ImageMagick's own histogram when the fixtures were made:
     "magick src.pgm -format %c histogram:info:-". */
  unsigned long histogram[256];
  REQUIRE(imCalcGrayHistogram(src, histogram, 0) != 0);

  CHECK(histogram[0] == 8);
  CHECK(histogram[1] == 7);
  CHECK(histogram[4] == 6);
  CHECK(histogram[7] == 6);
  CHECK(histogram[10] == 3);
  CHECK(histogram[12] == 1);

  unsigned long total = 0;
  for (int i = 0; i < 256; i++)
    total += histogram[i];
  CHECK(total == 32 * 24);

  imImageDestroy(src);
}

TEST_CASE("golden: image statistics agree with an independent measurement")
{
  /* ImageMagick reported, on the same file and scaled from its Q16 range:
     mean 129.09, min 0, max 255, standard deviation 65.19. */
  imImage* src = load_golden("src.pgm");

  imStats stats;
  REQUIRE(imCalcImageStatistics(src, &stats) != 0);

  CHECK(stats.min == doctest::Approx(0.0));
  CHECK(stats.max == doctest::Approx(255.0));
  CHECK(stats.mean == doctest::Approx(129.09).epsilon(0.001));
  CHECK(stats.stddev == doctest::Approx(65.19).epsilon(0.01));

  imImageDestroy(src);
}

TEST_CASE("golden: the minimum and maximum filters match exactly, borders included")
{
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  REQUIRE(dst != NULL);

  SUBCASE("RankMinConvolve")
  {
    imImage* want = load_golden("min3.pgm");
    REQUIRE(imProcessRankMinConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("RankMaxConvolve")
  {
    imImage* want = load_golden("max3.pgm");
    REQUIRE(imProcessRankMaxConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("RangeConvolve is the difference of the two")
  {
    imImage* want = load_golden("range3.pgm");
    REQUIRE(imProcessRangeConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    imImageDestroy(want);
  }

  imImageDestroy(src);
  imImageDestroy(dst);
}

TEST_CASE("golden: gray morphology is the same pair of filters")
{
  /* Erode and dilate over a square structuring element are the minimum and
     maximum filters, so they are held to the same references -- which also
     pins the two families to each other. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  REQUIRE(dst != NULL);

  SUBCASE("Erode is the minimum filter")
  {
    imImage* want = load_golden("min3.pgm");
    REQUIRE(imProcessGrayMorphErode(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    imImageDestroy(want);
  }
  SUBCASE("Dilate is the maximum filter")
  {
    imImage* want = load_golden("max3.pgm");
    REQUIRE(imProcessGrayMorphDilate(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    imImageDestroy(want);
  }
  SUBCASE("Open is an erode followed by a dilate")
  {
    imImage* want = load_golden("open3.pgm");
    REQUIRE(imProcessGrayMorphOpen(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("Close is the other order")
  {
    imImage* want = load_golden("close3.pgm");
    REQUIRE(imProcessGrayMorphClose(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 0) == 0);
    check_actually_filtered(dst, src);

    /* Opening and closing are different operations; a build where one was
       wired to the other would pass each of the two cases above only if they
       compared against the same reference, so check they diverge. */
    imImage* opened = imImageCreateBased(src, -1, -1, -1, -1);
    REQUIRE(imProcessGrayMorphOpen(src, opened, 3) != 0);
    CHECK(worst_difference(dst, opened, 0) > 0);
    imImageDestroy(opened);

    imImageDestroy(want);
  }

  imImageDestroy(src);
  imImageDestroy(dst);
}

TEST_CASE("golden: the median filter matches exactly away from the border")
{
  /* The border is where the two libraries legitimately differ: the window
     runs off the edge and they fill it differently. Everything further in
     than half the kernel is unambiguous, and matches to the sample. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  REQUIRE(dst != NULL);

  SUBCASE("3x3")
  {
    imImage* want = load_golden("median3.pgm");
    REQUIRE(imProcessMedianConvolve(src, dst, 3) != 0);
    CHECK(worst_difference(dst, want, 1) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }
  SUBCASE("5x5")
  {
    /* A larger window, so a bug in how the window is gathered rather than
       sorted has somewhere to show. */
    imImage* want = load_golden("median5.pgm");
    REQUIRE(imProcessMedianConvolve(src, dst, 5) != 0);
    CHECK(worst_difference(dst, want, 2) == 0);
    check_actually_filtered(dst, src);
    imImageDestroy(want);
  }

  SUBCASE("and it is not simply the minimum or the maximum")
  {
    /* The three rank filters share their window-gathering code, so a median
       that returned the wrong element of the sorted window would still agree
       with itself everywhere. */
    imImage* median = imImageCreateBased(src, -1, -1, -1, -1);
    imImage* other = imImageCreateBased(src, -1, -1, -1, -1);
    REQUIRE(imProcessMedianConvolve(src, median, 3) != 0);

    REQUIRE(imProcessRankMinConvolve(src, other, 3) != 0);
    CHECK(worst_difference(median, other, 1) > 0);

    REQUIRE(imProcessRankMaxConvolve(src, other, 3) != 0);
    CHECK(worst_difference(median, other, 1) > 0);

    imImageDestroy(median);
    imImageDestroy(other);
  }

  imImageDestroy(src);
  imImageDestroy(dst);
}

TEST_CASE("golden: the mean filter matches within the rounding difference")
{
  /* The only one of these that is not exact. Both libraries average the same
     nine samples; they disagree only on how the average is rounded back to a
     byte, which is at most one. A bound of 1 still fails on anything
     structural -- a shifted window or a wrong divisor moves samples by tens. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreateBased(src, -1, -1, -1, -1);
  imImage* want = load_golden("mean3.pgm");
  REQUIRE(dst != NULL);

  REQUIRE(imProcessMeanConvolve(src, dst, 3) != 0);
  CHECK(worst_difference(dst, want, 1) <= 1);
  check_actually_filtered(dst, src);

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}


/* ================================================================== *
 * A second batch, covering operations outside the rank/morphology
 * family. The agreement observed when the fixtures were made is noted
 * on each; the regeneration script records it too.
 * ================================================================== */

TEST_CASE("golden: nearest-neighbour resize to an exact multiple")
{
  /* Only the enlargement. IM and ImageMagick disagree completely about which
     source pixel a destination pixel samples when shrinking -- 223 levels
     apart on this source -- and neither convention is wrong, so there is no
     reference to compare a reduction against. Doubling is unambiguous: every
     destination pixel has exactly one source pixel over it. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreate(64, 48, IM_GRAY, IM_BYTE);
  REQUIRE(dst != NULL);

  REQUIRE(imProcessResize(src, dst, 0) != 0);

  imImage* want = load_golden("resize_near2x.pgm");
  CHECK(worst_difference(dst, want, 0) == 0);

  /* Each 2x2 block of the result is one source pixel repeated, which is what
     nearest neighbour at an integer factor means -- asserted separately so a
     reference that happened to be a blur could not slip through. */
  for (int y = 0; y < 24; y++)
  {
    for (int x = 0; x < 32; x++)
    {
      CAPTURE(x); CAPTURE(y);
      imbyte v = ((imbyte*)src->data[0])[y*32 + x];
      CHECK(((imbyte*)dst->data[0])[(2*y)*64 + 2*x] == v);
      CHECK(((imbyte*)dst->data[0])[(2*y)*64 + 2*x + 1] == v);
      CHECK(((imbyte*)dst->data[0])[(2*y + 1)*64 + 2*x] == v);
      CHECK(((imbyte*)dst->data[0])[(2*y + 1)*64 + 2*x + 1] == v);
    }
  }

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}

TEST_CASE("golden: Otsu picks the same threshold as an independent implementation")
{
  /* The strongest of these, because the level is not given to the operation:
     both libraries derive it from the histogram, so agreeing on the resulting
     mask means agreeing on the algorithm rather than on applying a number
     someone chose. IM reports the level it used -- 128 on this source. */
  imImage* src = load_golden("src.pgm");
  imImage* dst = imImageCreate(src->width, src->height, IM_BINARY, IM_BYTE);
  REQUIRE(dst != NULL);

  int level = imProcessOtsuThreshold(src, dst);
  CHECK(level == 128);

  /* IM writes 0 and 1; the reference is 0 and 255. */
  imImage* want = load_golden("otsu.pgm");
  for (int i = 0; i < src->count; i++)
  {
    CAPTURE(i);
    int got = ((imbyte*)dst->data[0])[i];
    int expected = ((imbyte*)want->data[0])[i] ? 1 : 0;
    CHECK(got == expected);
  }

  /* And it is a real split rather than everything landing on one side. */
  int ones = 0;
  for (int i = 0; i < src->count; i++)
    ones += ((imbyte*)dst->data[0])[i];
  CHECK(ones > src->count / 10);
  CHECK(ones < (src->count * 9) / 10);

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}

TEST_CASE("golden: binary morphology matches on a bilevel image")
{
  /* The gray erode and dilate are already pinned above; these are the
     separate binary implementations, which take a different path entirely --
     imProcessBinMorphConvolve with a kernel of ones rather than a rank
     filter. The fixture is 0 and 255, IM works in 0 and 1. */
  imImage* fixture = load_golden("src_bin.pgm");
  imImage* src = imImageCreate(fixture->width, fixture->height, IM_BINARY, IM_BYTE);
  REQUIRE(src != NULL);
  for (int i = 0; i < fixture->count; i++)
    ((imbyte*)src->data[0])[i] = ((imbyte*)fixture->data[0])[i] ? 1 : 0;

  imImage* dst = imImageCreate(src->width, src->height, IM_BINARY, IM_BYTE);
  REQUIRE(dst != NULL);

  SUBCASE("dilate matches everywhere")
  {
    REQUIRE(imProcessBinMorphDilate(src, dst, 3, 1) != 0);
    imImage* want = load_golden("bin_dilate3.pgm");
    for (int i = 0; i < src->count; i++)
    {
      CAPTURE(i);
      CHECK((int)((imbyte*)dst->data[0])[i] ==
            (((imbyte*)want->data[0])[i] ? 1 : 0));
    }
    imImageDestroy(want);
  }

  SUBCASE("erode matches away from the border")
  {
    /* Thirteen border samples differ, for the same padding reason as the
       median: an erode has to decide what lies beyond the edge. */
    REQUIRE(imProcessBinMorphErode(src, dst, 3, 1) != 0);
    imImage* want = load_golden("bin_erode3.pgm");
    for (int y = 1; y < src->height - 1; y++)
    {
      for (int x = 1; x < src->width - 1; x++)
      {
        CAPTURE(x); CAPTURE(y);
        int i = y*src->width + x;
        CHECK((int)((imbyte*)dst->data[0])[i] ==
              (((imbyte*)want->data[0])[i] ? 1 : 0));
      }
    }
    imImageDestroy(want);
  }

  SUBCASE("and the two are not the same operation")
  {
    imImage* eroded = imImageCreate(src->width, src->height, IM_BINARY, IM_BYTE);
    REQUIRE(imProcessBinMorphErode(src, eroded, 3, 1) != 0);
    REQUIRE(imProcessBinMorphDilate(src, dst, 3, 1) != 0);
    CHECK(memcmp(eroded->data[0], dst->data[0], src->count) != 0);
    imImageDestroy(eroded);
  }

  imImageDestroy(fixture);
  imImageDestroy(src);
  imImageDestroy(dst);
}

TEST_CASE("golden: RGB to gray matches the Rec601 luma transform")
{
  /* imConvertColorSpace applies Rec601 luma. ImageMagick 7 would work in
     linear light for -colorspace Gray and give a quite different answer, so
     the reference was made with -grayscale Rec601Luma; the two then agree to
     within the rounding, which is 1.

     This is the only case here from libim rather than libim_process, and it
     covers the largest single file still thinly tested. */
  imImage* src = load_golden("src_rgb.ppm");
  REQUIRE(imColorModeSpace(src->color_space) == IM_RGB);

  imImage* dst = imImageCreate(src->width, src->height, IM_GRAY, IM_BYTE);
  REQUIRE(dst != NULL);
  REQUIRE(imConvertColorSpace(src, dst) == IM_ERR_NONE);

  imImage* want = load_golden("rgb2gray601.pgm");
  CHECK(worst_difference(dst, want, 0) <= 1);

  /* A conversion that returned one channel, or the unweighted average, would
     also be "close" on some images -- so pin the weighting where the three
     channels differ most. */
  int worst_vs_average = 0;
  for (int i = 0; i < src->count; i++)
  {
    int r = ((imbyte**)src->data)[0][i];
    int g = ((imbyte**)src->data)[1][i];
    int b = ((imbyte**)src->data)[2][i];
    int average = (r + g + b) / 3;
    int diff = (int)((imbyte*)dst->data[0])[i] - average;
    if (diff < 0) diff = -diff;
    if (diff > worst_vs_average) worst_vs_average = diff;
  }
  CHECK(worst_vs_average > 20);

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}


/* ================================================================== *
 * Colour space conversions
 *
 * These reach the largest file in libim that is still thinly covered,
 * im_convertcolor.cpp, and they check the whole path rather than the inline
 * maths in im_color.h that test_convert.cpp already pins: the transfer
 * function, the matrix, and the quantization back to bytes, end to end
 * against a second implementation.
 *
 * Generating the references needed one non-obvious step, recorded in the
 * regeneration script: "-set colorspace sRGB" after the conversion. Without
 * it ImageMagick converts back to sRGB on the way into a PPM, since PPM is an
 * RGB format and version 7 tracks what a file holds. The reference then
 * disagrees by up to 251 levels and reads like a defect in this library
 * rather than a round trip in the reference.
 * ================================================================== */

namespace {

/* Per-plane worst difference across a colour image. */
int worst_plane_difference(const imImage* a, const imImage* b, int plane)
{
  int worst = 0;
  for (int i = 0; i < a->count; i++)
  {
    int diff = (int)((imbyte**)a->data)[plane][i] -
               (int)((imbyte**)b->data)[plane][i];
    if (diff < 0) diff = -diff;
    if (diff > worst) worst = diff;
  }
  return worst;
}

} /* namespace */

TEST_CASE("golden: RGB to Y'CbCr matches the ITU-R 601 reference")
{
  /* Nonlinear throughout, correctly: Y'CbCr is defined on gamma-encoded
     R'G'B', and imConvertColorSpace applies no transfer function on this
     path. Agreement here is agreement about the 601 matrix and the zero
     shift together. */
  imImage* src = load_golden("src_rgb.ppm");
  imImage* dst = imImageCreate(src->width, src->height, IM_YCBCR, IM_BYTE);
  REQUIRE(dst != NULL);
  REQUIRE(imConvertColorSpace(src, dst) == IM_ERR_NONE);

  imImage* want = load_golden("rgb2ycbcr.ppm");
  for (int p = 0; p < 3; p++)
  {
    CAPTURE(p);
    CHECK(worst_plane_difference(dst, want, p) <= 1);
  }

  /* And it is a real transform, not a copy: chroma has to collapse towards
     the zero shift while luma keeps the full spread. */
  int y_min = 255, y_max = 0, cb_min = 255, cb_max = 0;
  for (int i = 0; i < dst->count; i++)
  {
    int y = ((imbyte**)dst->data)[0][i];
    int cb = ((imbyte**)dst->data)[1][i];
    if (y < y_min) y_min = y;
    if (y > y_max) y_max = y;
    if (cb < cb_min) cb_min = cb;
    if (cb > cb_max) cb_max = cb;
  }
  CHECK(y_max - y_min > 100);
  CHECK(cb_max - cb_min < y_max - y_min);

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}

TEST_CASE("golden: RGB to CIE XYZ matches through the transfer function")
{
  /* The one that actually exercises linearisation. imConvertColorSpace calls
     imColorTransfer2Linear on each channel before applying the sRGB matrix,
     and agreement to within the rounding says both halves are right --
     skipping the transfer function, or applying it twice, moves samples by
     tens rather than by one. */
  imImage* src = load_golden("src_rgb.ppm");
  imImage* dst = imImageCreate(src->width, src->height, IM_XYZ, IM_BYTE);
  REQUIRE(dst != NULL);
  REQUIRE(imConvertColorSpace(src, dst) == IM_ERR_NONE);

  imImage* want = load_golden("rgb2xyz.ppm");
  for (int p = 0; p < 3; p++)
  {
    CAPTURE(p);
    CHECK(worst_plane_difference(dst, want, p) <= 1);
  }

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}

TEST_CASE("golden: RGB to CIE L*a*b* matches once the encoding is accounted for")
{
  imImage* src = load_golden("src_rgb.ppm");
  imImage* dst = imImageCreate(src->width, src->height, IM_LAB, IM_BYTE);
  REQUIRE(dst != NULL);
  REQUIRE(imConvertColorSpace(src, dst) == IM_ERR_NONE);

  imImage* want = load_golden("rgb2lab.ppm");

  SUBCASE("lightness is directly comparable")
  {
    CHECK(worst_plane_difference(dst, want, 0) <= 1);
  }

  SUBCASE("the chroma axes differ by a known scale, not by a computation")
  {
    /* IM computes a = 2.5*(fX - fY) and packs -0.5..0.5 into a byte, giving
       637.5*d + 127.5. The standard, and ImageMagick, use a = 500*(fX - fY)
       over -128..127, giving 500*d + 128. So the two are related by

           a_IM = (a_reference - 128) * 1.275 + 127.5

       and agree once that is applied. Asserting the relation rather than
       skipping these planes is the difference between checking IM's chroma
       against a second implementation and not checking it at all -- an
       encoding choice is not a licence to leave two thirds of the conversion
       unverified. */
    for (int p = 1; p < 3; p++)
    {
      CAPTURE(p);
      double worst = 0;
      for (int i = 0; i < src->count; i++)
      {
        double reference = (double)((imbyte**)want->data)[p][i];
        double expected = (reference - 128.0) * 1.275 + 127.5;
        double got = (double)((imbyte**)dst->data)[p][i];
        double diff = got - expected;
        if (diff < 0) diff = -diff;
        if (diff > worst) worst = diff;
      }

      /* Measured at 1.8: two independent quantizations to a byte, one of
         them through the scale factor. A computation that actually differed
         would be tens of levels out, not two. */
      CHECK(worst <= 2.0);
    }
  }

  imImageDestroy(src);
  imImageDestroy(dst);
  imImageDestroy(want);
}
