/** \file
 * \brief Decorrelation Stretch
 *
 * See Copyright Notice in im_lib.h
 */


#include <im.h>
#include <im_util.h>
#include <im_math.h>
#include <im_color.h>

#include "im_process_counter.h"
#include "im_process_pnt.h"
#include "im_process_check.h"

#include <stdlib.h>
#include <memory.h>
#include <math.h>
#include <assert.h>


/* The decorrelation stretch, in the form MATLAB's decorrstretch uses:

     T   = diag(target) . V . L^(-1/2) . V^T
     out = T (in - mean) + mean

   where V L V^T is the eigen-decomposition of the band covariance and
   target[i] = scale * stddev[i] of band i. Each output band is stretched to
   "scale" times its own original spread, which is what keeps the result in
   gamut; equalising the bands to a single common sigma instead sends the luma
   of a YUV-like space to roughly -230..420 on byte data.

   Two properties of that T are worth knowing, because the tests lean on both:

   - the output covariance is exactly diag(target^2). Not approximately: the
     whitening is exact, so the off-diagonal terms cancel to rounding. That is
     an exact assertion rather than a tolerance.

   - T does not depend on the sign or the order of the eigenvectors, only on
     the subspaces. Two eigen-solvers that disagree completely about V still
     agree about T, which is what lets the golden images be generated by
     LAPACK and checked against the Jacobi below.

   T is also unchanged if the covariance is scaled by a constant -- the
   sqrt cancels between target and L^(-1/2) -- so the population/sample
   divisor makes no difference to the result.

   Two divergences from JPL's Algorithm Theoretical Basis Document for
   Decorrelation Stretch, which is where the technique comes from, both
   deliberate:

   - the ATBD targets a single absolute output standard deviation for every
     band (50, chosen to fill the 0-255 range of byte data) and re-centres the
     result on the middle of that range. That bakes in both a data type and a
     taste. Here each band is targeted at "scale" times its own standard
     deviation and the mean is preserved, which is what MATLAB's decorrstretch
     does, is data-type independent, and leaves the choice of how hard to
     stretch to the caller. Multiply by the appropriate scale to reproduce the
     ATBD's behaviour.

   - the ATBD accumulates the covariance in the one-pass form,
     SUMXY - SUMX*SUMY/n, as im_statistics.cpp does. See DoMoments below for
     why this file does not.

   ON FORMING THE COVARIANCE AT ALL

   Crabu, Pes and Rodriguez, "Numerical Methods for Decorrelation Stretch"
   (Mathematics 2025, 13, 3297) make the sharper objection that building the
   covariance is the wrong move to begin with: it is A^T A, which squares the
   condition number and is not backward stable, and they get better accuracy
   by taking the SVD of the centred data directly, or a Q-less QR followed by
   an SVD of the 3x3 triangular factor. They are right, and it does not matter
   here. Measured against their SVD method on synthetic data of increasing
   collinearity, agreeing to a relative:

     cond(covariance)     1e3     1e5     1e7     1e9    1e11    1e13
     agreement           1e-12   2e-10   9e-09   7e-07   5e-05   exact*

   * beyond about 1e12 the rank guard below fires first and both methods take
     the degenerate path.

   The golden fixture in test/fixtures/golden has a condition number of 126,
   and natural photographs sit between 10 and 1000, where the disagreement is
   at 1e-12 -- ten orders of magnitude below one level of an 8-bit channel.
   The error only reaches 1e-5 when the colour planes agree to five decimals,
   which no 8- or 16-bit image can even represent. The covariance route keeps
   this file to one Jacobi and no QR, and buys nothing worse than that.

   It would matter for multispectral data with many more than three planes, or
   for real-valued input with a large dynamic range. If this ever grows in
   that direction, that paper is the thing to implement, not a bigger Jacobi.

   The same reasoning fixes the rank threshold below. Forming the covariance
   puts a precision floor under the eigenvalues at roughly machine epsilon
   relative to the largest, so a cutoff at 1e-12 there sits just above the
   noise -- tighter would be pretending to a resolution the covariance no
   longer has, and looser would discard directions that are still real. */


/*************************************************************************
  3x3 linear algebra. Small, fixed size, row-major, and private to this file.
*************************************************************************/

static void iMatMul3(const double* a, const double* b, double* r)
{
  for (int i = 0; i < 3; i++)
  {
    for (int j = 0; j < 3; j++)
    {
      double s = 0.0;
      for (int k = 0; k < 3; k++)
        s += a[i*3+k] * b[k*3+j];
      r[i*3+j] = s;
    }
  }
}

/* Inverse by the adjugate. Returns zero if the matrix is singular, which for
   the colour-space matrices here means the caller was handed a bad custom
   one. */
static int iMatInv3(const double* m, double* r)
{
  double c00 = m[4]*m[8] - m[5]*m[7];
  double c01 = m[5]*m[6] - m[3]*m[8];
  double c02 = m[3]*m[7] - m[4]*m[6];

  double det = m[0]*c00 + m[1]*c01 + m[2]*c02;
  if (det == 0.0)
    return 0;

  double d = 1.0 / det;

  r[0] = c00 * d;
  r[1] = (m[2]*m[7] - m[1]*m[8]) * d;
  r[2] = (m[1]*m[5] - m[2]*m[4]) * d;
  r[3] = c01 * d;
  r[4] = (m[0]*m[8] - m[2]*m[6]) * d;
  r[5] = (m[2]*m[3] - m[0]*m[5]) * d;
  r[6] = c02 * d;
  r[7] = (m[1]*m[6] - m[0]*m[7]) * d;
  r[8] = (m[0]*m[4] - m[1]*m[3]) * d;

  return 1;
}

/* Cyclic Jacobi for a 3x3 real symmetric matrix. "a" is destroyed; on return
   lambda holds the eigenvalues and v their eigenvectors, one per column.

   Jacobi rather than the closed-form cubic. The images this operation exists
   for have their colours strung out along a single axis, so the covariance is
   close to singular -- precisely where Cardano's formula loses most of its
   precision, and the eigenvalue it gets worst is the small one the stretch
   turns around and divides by. Jacobi stays accurate there, and 3x3 converges
   in a handful of sweeps, so the cost is not worth the trade. */
static void iJacobi3(double* a, double* lambda, double* v)
{
  int i, j, p, q, sweep;

  memset(v, 0, 9*sizeof(double));
  v[0] = v[4] = v[8] = 1.0;

  for (sweep = 0; sweep < 50; sweep++)
  {
    double off = a[1]*a[1] + a[2]*a[2] + a[5]*a[5];
    double diag = a[0]*a[0] + a[4]*a[4] + a[8]*a[8];

    /* relative, so the test means the same thing whether the samples are
       bytes or normalised floats */
    if (off <= 1e-28 * (diag > 0.0? diag: 1.0))
      break;

    for (p = 0; p < 2; p++)
    {
      for (q = p+1; q < 3; q++)
      {
        double apq = a[p*3+q];
        if (apq == 0.0)
          continue;

        double theta = (a[q*3+q] - a[p*3+p]) / (2.0*apq);
        double t = (theta >= 0.0? 1.0: -1.0) / (fabs(theta) + sqrt(theta*theta + 1.0));
        double c = 1.0 / sqrt(t*t + 1.0);
        double s = t*c;

        for (i = 0; i < 3; i++)      /* columns p and q */
        {
          double aip = a[i*3+p], aiq = a[i*3+q];
          a[i*3+p] = c*aip - s*aiq;
          a[i*3+q] = s*aip + c*aiq;
        }
        for (j = 0; j < 3; j++)      /* rows p and q */
        {
          double apj = a[p*3+j], aqj = a[q*3+j];
          a[p*3+j] = c*apj - s*aqj;
          a[q*3+j] = s*apj + c*aqj;
        }
        for (i = 0; i < 3; i++)      /* accumulate the rotation */
        {
          double vip = v[i*3+p], viq = v[i*3+q];
          v[i*3+p] = c*vip - s*viq;
          v[i*3+q] = s*vip + c*viq;
        }
      }
    }
  }

  lambda[0] = a[0];
  lambda[1] = a[4];
  lambda[2] = a[8];
}


/*************************************************************************
  The colour spaces.
*************************************************************************/

/* Forward 3x3 matrices, row-major, applied to the space named by
   iDecorrIsLab: RGB for most of these, CIE L*a*b* for the L-prefixed ones.

   A WORD ON THE NAMES. YDS, YBR, YBK, YRE, LDS, LRE and LBK are the names
   DStretch (dstretch.com) gives the custom colour spaces it found useful on
   rock art. The coefficients are NOT DStretch's. They have never been
   published: its algorithm page describes these spaces only as
   "modifications of the YUV or LAB colorspaces that have been found to give
   good decorrelation stretch results on images of rock art", and gives no
   numbers anywhere. What is here is this library's reading of that sentence
   -- the base space with axes weighted before the covariance is taken, which
   redistributes the stretch toward the colours those axes carry -- so these
   produce results of the same character, not the same pixels.

   The structure is not guesswork even though the numbers are. DStretch's own
   handout says the enhancements were made "by manipulating colorspaces ... by
   adjusting the multipliers in the dialog displayed by the YXX and LXX
   buttons", and that they come in twins, "one with an L, one with a Y ...
   LDS and YDS, LRE and YRE, LBK and YBK, LYE and YYE". So: a base space, one
   multiplier per axis, and each enhancement existing over both bases. That is
   exactly the shape of this table, and why the twins here share their
   multipliers across Y'CbCr and L*a*b*.

   Anyone wanting DStretch's actual behaviour has two routes that need nothing
   from this file. Its YXX/LXX panel displays the multipliers behind each named
   colourspace -- those go into IM_DECORR_CUSTOM as they stand. And its Matrix
   button writes the finished 3x3 of a stretch to a text file, which can be
   loaded into an imDecorrelationTransform and applied directly.

   Note that no row here repeats another. IM_DECORR_YDS and IM_DECORR_LDS are
   the general-purpose ones, and damping luma while lifting both chroma axes is
   what makes them general-purpose: it hands the stretch to the colour
   differences rather than to the brightness, which is where faint pigment
   lives. Giving them a weight of 1 would have made them silent aliases of
   IM_DECORR_YUV and IM_DECORR_LAB, and a preset that is secretly another
   preset is worse than no preset.

   Weighting before the stretch is not cosmetic: the stretch equalises the
   variances it finds, so scaling an axis up beforehand makes the stretch give
   it proportionally less gain and the others more. Measured across these
   presets on a correlated image the outputs differ by 12 to 22 levels on
   average, so no two of these rows are the same operation, and a test asserts
   it. */

/* ITU-R 601, matching imColorRGB2YCbCr: Cb is the blue-yellow axis, Cr the
   red-green one. */
#define IM_DECORR_Y   0.299,  0.587,  0.114
#define IM_DECORR_CB -0.169, -0.331,  0.500
#define IM_DECORR_CR  0.500, -0.419, -0.081

/* the same three rows with a multiplier on the axis, which is the only knob
   the presets below turn */
#define IM_DECORR_YW(_w)  (_w)* 0.299, (_w)* 0.587, (_w)* 0.114
#define IM_DECORR_CBW(_w) (_w)*-0.169, (_w)*-0.331, (_w)* 0.500
#define IM_DECORR_CRW(_w) (_w)* 0.500, (_w)*-0.419, (_w)*-0.081

static const double iDecorrMatrix[][9] =
{
  /* IM_DECORR_RGB  */ { 1.0, 0.0, 0.0,   0.0, 1.0, 0.0,   0.0, 0.0, 1.0 },
  /* IM_DECORR_CRGB */ { 1.0, 0.0, 0.0,   0.0, 1.0, 0.0,   0.0, 0.0, 1.0 },
  /* IM_DECORR_YUV  */ { IM_DECORR_Y, IM_DECORR_CB, IM_DECORR_CR },
  /* IM_DECORR_LAB  */ { 1.0, 0.0, 0.0,   0.0, 1.0, 0.0,   0.0, 0.0, 1.0 },

  /* Y'CbCr with per-axis multipliers. Cb is the blue-yellow axis, Cr the
     red-cyan one, so lifting Cb hands the stretch to blues and yellows and
     lifting Cr hands it to reds. Damping luma at the same time gives the
     chroma axes proportionally more of it, which is what a "faint pigment"
     enhancement wants; keeping luma up is what a black-pigment one wants,
     since there the brightness is the signal. */
  /* IM_DECORR_YDS  */ { IM_DECORR_YW(0.80), IM_DECORR_CBW(1.20), IM_DECORR_CRW(1.20) },
  /* IM_DECORR_YBR  */ { IM_DECORR_YW(1.00), IM_DECORR_CBW(1.30), IM_DECORR_CRW(1.30) },
  /* IM_DECORR_YBK  */ { IM_DECORR_YW(1.30), IM_DECORR_CBW(1.30), IM_DECORR_CRW(0.70) },
  /* IM_DECORR_YRE  */ { IM_DECORR_YW(0.80), IM_DECORR_CBW(0.60), IM_DECORR_CRW(1.70) },
  /* IM_DECORR_YRD  */ { IM_DECORR_YW(1.00), IM_DECORR_CBW(0.90), IM_DECORR_CRW(1.40) },
  /* IM_DECORR_YYE  */ { IM_DECORR_YW(0.80), IM_DECORR_CBW(1.60), IM_DECORR_CRW(0.85) },

  /* CIE L*a*b* with the same multipliers over its axes. a* is red-green and
     b* is yellow-blue, so the twin of a Cr-lifting Y enhancement lifts a*,
     and the twin of a Cb-lifting one lifts b*. The conversion is nonlinear
     and happens per pixel before this matrix is applied. */
  /* IM_DECORR_LDS  */ { 0.80, 0.0, 0.0,   0.0, 1.20, 0.0,   0.0, 0.0, 1.20 },
  /* IM_DECORR_LRE  */ { 0.80, 0.0, 0.0,   0.0, 1.70, 0.0,   0.0, 0.0, 0.60 },
  /* IM_DECORR_LBK  */ { 1.30, 0.0, 0.0,   0.0, 0.70, 0.0,   0.0, 0.0, 1.30 },
  /* IM_DECORR_LYE  */ { 0.80, 0.0, 0.0,   0.0, 0.85, 0.0,   0.0, 0.0, 1.60 }
};

#undef IM_DECORR_Y
#undef IM_DECORR_CB
#undef IM_DECORR_CR
#undef IM_DECORR_YW
#undef IM_DECORR_CBW
#undef IM_DECORR_CRW

static int iDecorrIsLab(int color_space)
{
  return color_space == IM_DECORR_LAB ||
         color_space == IM_DECORR_LDS ||
         color_space == IM_DECORR_LRE ||
         color_space == IM_DECORR_LBK ||
         color_space == IM_DECORR_LYE;
}

static int iDecorrUseCorrelation(int color_space)
{
  return color_space == IM_DECORR_CRGB;
}

/* Fills "forward" with the matrix for the space, or returns zero if the space
   is not one, or if a custom matrix was asked for and none was supplied. */
static int iDecorrForward(int color_space, const double* custom_matrix, double* forward)
{
  if (color_space == IM_DECORR_CUSTOM)
  {
    if (!custom_matrix)
      return 0;

    memcpy(forward, custom_matrix, 9*sizeof(double));
    return 1;
  }

  if (color_space < 0 || color_space > IM_DECORR_LYE)
    return 0;

  memcpy(forward, iDecorrMatrix[color_space], 9*sizeof(double));
  return 1;
}

/* R'G'B' to CIE L*a*b*, and back. The same sequence iDoConvert2Lab in
   im_convertcolor.cpp uses, but kept in double from end to end instead of
   being quantized into an image: L stays in 0-1 and a,b in -0.5..0.5. That
   avoids a temporary image, and avoids IM's byte L*a*b* packing, which puts
   a and b on a 637.5 scale rather than the standard 500 and would cost
   precision here for nothing. */
static void iDecorrRGB2Lab(double r, double g, double b, double* lab)
{
  r = imColorTransfer2Linear(r);
  g = imColorTransfer2Linear(g);
  b = imColorTransfer2Linear(b);

  imColorRGB2XYZ(r, g, b, r, g, b);
  imColorXYZ2Lab(r, g, b, lab[0], lab[1], lab[2]);
}

static void iDecorrLab2RGB(const double* lab, double* rgb)
{
  double x, y, z;

  imColorLab2XYZ(lab[0], lab[1], lab[2], x, y, z);
  imColorXYZ2RGB(x, y, z, rgb[0], rgb[1], rgb[2]);

  rgb[0] = imColorTransfer2Nonlinear(rgb[0]);
  rgb[1] = imColorTransfer2Nonlinear(rgb[1]);
  rgb[2] = imColorTransfer2Nonlinear(rgb[2]);
}


/*************************************************************************
  Reading the image.
*************************************************************************/

/* One pixel, in the space the covariance is taken in: the raw components for
   the linear spaces, L*a*b* for the others. The colour-space matrix is NOT
   applied here -- it is folded into the transform afterwards, which is
   algebraically the same thing and one multiply per pixel cheaper. */
template <class T>
static inline void iDecorrSample(T** data, int i, int is_lab,
                                 double type_min, double type_max, double* c)
{
  if (is_lab)
  {
    double r = imColorReconstruct(data[0][i], (T)type_min, (T)type_max);
    double g = imColorReconstruct(data[1][i], (T)type_min, (T)type_max);
    double b = imColorReconstruct(data[2][i], (T)type_min, (T)type_max);

    iDecorrRGB2Lab(r, g, b, c);
  }
  else
  {
    c[0] = (double)data[0][i];
    c[1] = (double)data[1][i];
    c[2] = (double)data[2][i];
  }
}

/* Two passes, means then centred cross-products.

   Deliberately not the one-pass sum-of-squares form DoStats uses in
   im_statistics.cpp. For a byte band with mean 200 and a standard deviation
   of 3 -- an ordinary shadowed rock face -- E[x*x] is about 40009 against a
   mean square of 40000, so the subtraction throws away four significant
   digits before the work starts. This routine then inverts the result and
   takes its square root, which turns that error into a visible one. The
   second read costs nothing next to that. */
template <class T>
static int DoMoments(T** data, const imbyte* mask, int width, int height,
                     int is_lab, double type_min, double type_max,
                     double* mean, double* cov, double* sample_count, int counter)
{
  int count = width*height;
  double s0 = 0.0, s1 = 0.0, s2 = 0.0, n = 0.0;
  double c00 = 0.0, c01 = 0.0, c02 = 0.0, c11 = 0.0, c12 = 0.0, c22 = 0.0;
  int i;

  IM_INT_PROCESSING;

#ifdef _OPENMP
#pragma omp parallel for if (IM_OMP_MINCOUNT(count)) reduction (+:s0, s1, s2, n)
#endif
  for (i = 0; i < count; i++)
  {
    if (i % width == 0)
    {
#ifdef _OPENMP
#pragma omp flush (processing)
#endif
    }
    IM_BEGIN_PROCESSING;

    if (!mask || mask[i])
    {
      double c[3];
      iDecorrSample(data, i, is_lab, type_min, type_max, c);

      s0 += c[0];
      s1 += c[1];
      s2 += c[2];
      n += 1.0;
    }

    if (i % width == 0)
    {
      IM_COUNT_PROCESSING;
#ifdef _OPENMP
#pragma omp flush (processing)
#endif
    }
    IM_END_PROCESSING;
  }

  if (processing == IM_PROCESS_ABORT)
    return IM_PROCESS_ABORT;

  *sample_count = n;

  if (n < 2.0)
  {
    /* nothing to measure; the caller turns this into the identity */
    mean[0] = n > 0.0? s0: 0.0;
    mean[1] = n > 0.0? s1: 0.0;
    mean[2] = n > 0.0? s2: 0.0;
    memset(cov, 0, 9*sizeof(double));
    return IM_PROCESS_OK;
  }

  mean[0] = s0/n;
  mean[1] = s1/n;
  mean[2] = s2/n;

  {
    double m0 = mean[0], m1 = mean[1], m2 = mean[2];

#ifdef _OPENMP
#pragma omp parallel for if (IM_OMP_MINCOUNT(count)) \
                         reduction (+:c00, c01, c02, c11, c12, c22)
#endif
    for (i = 0; i < count; i++)
    {
      if (i % width == 0)
      {
#ifdef _OPENMP
#pragma omp flush (processing)
#endif
      }
      IM_BEGIN_PROCESSING;

      if (!mask || mask[i])
      {
        double c[3];
        iDecorrSample(data, i, is_lab, type_min, type_max, c);

        double d0 = c[0] - m0, d1 = c[1] - m1, d2 = c[2] - m2;

        c00 += d0*d0;  c01 += d0*d1;  c02 += d0*d2;
                       c11 += d1*d1;  c12 += d1*d2;
                                      c22 += d2*d2;
      }

      if (i % width == 0)
      {
        IM_COUNT_PROCESSING;
#ifdef _OPENMP
#pragma omp flush (processing)
#endif
      }
      IM_END_PROCESSING;
    }
  }

  /* n-1, as imStats uses. The choice does not reach the result: scaling the
     covariance by a constant scales the eigenvalues and the target standard
     deviations by matching amounts that cancel in the transform. */
  {
    double d = n - 1.0;

    cov[0] = c00/d;  cov[1] = c01/d;  cov[2] = c02/d;
    cov[3] = c01/d;  cov[4] = c11/d;  cov[5] = c12/d;
    cov[6] = c02/d;  cov[7] = c12/d;  cov[8] = c22/d;
  }

  return processing;
}


/*************************************************************************
  Building the transform.
*************************************************************************/

static void iDecorrBuild(const double* mean_c, const double* cov_c, double sample_count,
                         const double* forward, double scale, int use_correlation,
                         imDecorrelationTransform* transform)
{
  double inverse[9], cov_w[9], a[9], v[9], lambda[3], whiten[9], tmp[9];
  double sigma[3], gain[3];
  int i, j, k;

  memcpy(transform->mean, mean_c, 3*sizeof(double));

  /* to the working space: cov_w = M cov M^T */
  for (i = 0; i < 3; i++)
    for (j = 0; j < 3; j++)
    {
      double s = 0.0;
      for (k = 0; k < 3; k++)
        s += forward[i*3+k] * cov_c[k*3+j];
      tmp[i*3+j] = s;
    }
  for (i = 0; i < 3; i++)
    for (j = 0; j < 3; j++)
    {
      double s = 0.0;
      for (k = 0; k < 3; k++)
        s += tmp[i*3+k] * forward[j*3+k];
      cov_w[i*3+j] = s;
    }

  for (i = 0; i < 3; i++)
  {
    sigma[i] = cov_w[i*3+i] > 0.0? sqrt(cov_w[i*3+i]): 0.0;
    transform->target[i] = scale * sigma[i];
  }

  memcpy(a, cov_w, 9*sizeof(double));

  /* The correlation variant standardizes the bands before decorrelating, so
     a dark band counts for as much as a bright one. The output covariance is
     still exactly diag(target^2) -- the standardizing diagonal cancels
     against its own inverse on the way back out. */
  if (use_correlation)
  {
    for (i = 0; i < 3; i++)
      for (j = 0; j < 3; j++)
      {
        double d = sigma[i]*sigma[j];
        a[i*3+j] = d > 0.0? a[i*3+j]/d: (i == j? 1.0: 0.0);
      }
  }

  iJacobi3(a, lambda, v);

  /* largest first, so stddev[] reads as the shape of the colour cloud */
  for (i = 0; i < 2; i++)
  {
    int big = i;
    for (j = i+1; j < 3; j++)
      if (lambda[j] > lambda[big]) big = j;

    if (big != i)
    {
      double t = lambda[i]; lambda[i] = lambda[big]; lambda[big] = t;
      for (k = 0; k < 3; k++)
      {
        t = v[k*3+i]; v[k*3+i] = v[k*3+big]; v[k*3+big] = t;
      }
    }
  }

  /* A direction with no measurable spread is left alone rather than
     amplified. Gain 1 and not 0: zeroing it would flatten a colour cloud that
     is merely thin onto a plane, which is a visible and wrong-looking change,
     where leaving it is simply the absence of a stretch there.

     MATLAB's decorrstretch uses 0 here, via the pseudoinverse of the
     eigenvalue matrix. Crabu, Pes and Rodriguez (see the note at the top)
     show what that costs: the transform becomes an orthogonal projection onto
     the non-degenerate subspace, the output planes come back still
     correlated, and "DS has practically no effect". Their own recommendation
     for a constant or linearly dependent plane is to take it out, process the
     rest, and put it back untouched -- which, for a transform that has to
     return an image of the same shape, is what gain 1 does. */
  transform->rank = 0;
  for (i = 0; i < 3; i++)
  {
    transform->stddev[i] = lambda[i] > 0.0? sqrt(lambda[i]): 0.0;

    if (lambda[i] > 1e-12 * (lambda[0] > 0.0? lambda[0]: 1.0) && sample_count >= 2.0)
    {
      gain[i] = 1.0 / sqrt(lambda[i]);
      transform->rank++;
    }
    else
      gain[i] = 1.0;
  }

  /* whiten = V diag(gain) V^T. Symmetric, and a function of the covariance
     alone -- it does not depend on which eigenvector the solver picked or in
     what order, which is what lets these results be checked against a
     completely different eigen-solver. */
  for (i = 0; i < 3; i++)
    for (j = 0; j < 3; j++)
    {
      double s = 0.0;
      for (k = 0; k < 3; k++)
        s += v[i*3+k] * gain[k] * v[j*3+k];
      whiten[i*3+j] = s;
    }

  /* In correlation mode the whitening was computed for standardized bands, so
     it has to standardize on the way in. Nothing is needed on the way out:
     diag(target) already carries each band's own spread, which is what the
     covariance mode's whitening supplies for itself.

       cov_out = diag(t) R^-1/2 . D cov_w D . R^-1/2 diag(t)
               = diag(t) R^-1/2  R  R^-1/2 diag(t) = diag(t^2)

     the same exact result as the covariance mode. */
  if (use_correlation)
  {
    for (i = 0; i < 3; i++)
      for (j = 0; j < 3; j++)
        whiten[i*3+j] = sigma[j] > 0.0? whiten[i*3+j]/sigma[j]: whiten[i*3+j];
  }

  /* scale each band to its own target: T_w = diag(target) . whiten */
  for (i = 0; i < 3; i++)
    for (j = 0; j < 3; j++)
      tmp[i*3+j] = transform->target[i] * whiten[i*3+j];

  /* and back out of the working space: matrix = M^-1 T_w M.
     iDecorrCalc has already established that the inverse exists. */
  {
    double half[9];

    iMatInv3(forward, inverse);
    iMatMul3(inverse, tmp, half);
    iMatMul3(half, forward, transform->matrix);
  }

  /* Collapse the centring into a constant, so applying the transform is one
     multiply-add and there is only one form of it to get wrong. */
  for (i = 0; i < 3; i++)
  {
    double s = 0.0;
    for (j = 0; j < 3; j++)
      s += transform->matrix[i*3+j] * mean_c[j];
    transform->offset[i] = mean_c[i] - s;
  }
}


/*************************************************************************
  Applying it.
*************************************************************************/

/* Rounded, then clipped, then cast -- in that order, and all of it in double.
   imRound returns an int, so rounding an IM_INT result that lands near the
   top of the range would overflow before there was anything to clip.

   Rounded rather than truncated, which is the opposite of what line_op in
   im_tonegamut.cpp does. The transform is signed and centred on the mean, so
   truncation would bias every band half a level toward zero and leave the
   output covariance -- the one thing this operation actually promises -- a
   little wrong on purpose. The golden generator rounds to match. */
template <class T>
static inline T iDecorrStore(double value, double min, double max)
{
  value = value < 0.0? value - 0.5: value + 0.5;

  if (value <= min) return (T)min;
  if (value >= max) return (T)max;

  return (T)value;
}

template <> inline float iDecorrStore<float>(double value, double, double)
{
  return (float)value;
}

template <> inline double iDecorrStore<double>(double value, double, double)
{
  return value;
}

template <class T>
static int DoApply(T** src_data, T** dst_data, int width, int height,
                   const imDecorrelationTransform* transform,
                   double type_min, double type_max, int counter)
{
  int count = width*height;
  int is_lab = iDecorrIsLab(transform->color_space);
  const double* m = transform->matrix;
  const double* o = transform->offset;
  int i;

  IM_INT_PROCESSING;

#ifdef _OPENMP
#pragma omp parallel for if (IM_OMP_MINCOUNT(count))
#endif
  for (i = 0; i < count; i++)
  {
    if (i % width == 0)
    {
#ifdef _OPENMP
#pragma omp flush (processing)
#endif
    }
    IM_BEGIN_PROCESSING;

    {
      /* All three components are read before any is written, so the source
         and the destination may be the same image. */
      double c[3], r[3];

      iDecorrSample(src_data, i, is_lab, type_min, type_max, c);

      r[0] = m[0]*c[0] + m[1]*c[1] + m[2]*c[2] + o[0];
      r[1] = m[3]*c[0] + m[4]*c[1] + m[5]*c[2] + o[1];
      r[2] = m[6]*c[0] + m[7]*c[1] + m[8]*c[2] + o[2];

      if (is_lab)
      {
        double rgb[3];
        iDecorrLab2RGB(r, rgb);

        dst_data[0][i] = imColorQuantize(rgb[0], (T)type_min, (T)type_max);
        dst_data[1][i] = imColorQuantize(rgb[1], (T)type_min, (T)type_max);
        dst_data[2][i] = imColorQuantize(rgb[2], (T)type_min, (T)type_max);
      }
      else
      {
        dst_data[0][i] = iDecorrStore<T>(r[0], type_min, type_max);
        dst_data[1][i] = iDecorrStore<T>(r[1], type_min, type_max);
        dst_data[2][i] = iDecorrStore<T>(r[2], type_min, type_max);
      }
    }

    if (i % width == 0)
    {
      IM_COUNT_PROCESSING;
#ifdef _OPENMP
#pragma omp flush (processing)
#endif
    }
    IM_END_PROCESSING;
  }

  return processing;
}


/*************************************************************************
  Preconditions and dispatch.
*************************************************************************/

/* Two different ranges, and conflating them is a real bug rather than a
   tidiness point.

   iDecorrClipRange is the representable range of the data type, used to clip
   the linear path's result. It is deliberately not imColorMax, which is
   scaled for colour conversion and reports 8388607 for IM_INT and 1 for the
   real types.

   iDecorrColorRange is imColorMin/imColorMax, and is what the L*a*b* path
   must use, because that path is a colour conversion and normalizes through
   imColorReconstruct and imColorQuantize exactly as im_convertcolor.cpp does.
   Handing those the full IM_INT range instead makes imColorQuantize compute
   range = 2^32 and then imRound(value*range - 0.5) -- and imRound returns an
   int, so everything from the midpoint up overflows and every pixel comes
   back the same wrong number. IM_INT is the only type where the two ranges
   differ, which is exactly why it was the one that broke.

   A call is either L*a*b* or it is not, and each path touches only its own
   range, so one pair is threaded through and iDecorrRangeFor picks it. */
static int iDecorrClipRange(int data_type, double* min, double* max)
{
  switch(data_type)
  {
  case IM_BYTE:   *min = 0;            *max = 255;           return 1;
  case IM_SHORT:  *min = -32768;       *max = 32767;         return 1;
  case IM_USHORT: *min = 0;            *max = 65535;         return 1;
  case IM_INT:    *min = -2147483648.0; *max = 2147483647.0; return 1;
  case IM_FLOAT:  *min = 0;            *max = 1;             return 1;
  case IM_DOUBLE: *min = 0;            *max = 1;             return 1;
  }
  return 0;
}

static int iDecorrRangeFor(int data_type, int is_lab, double* min, double* max)
{
  if (is_lab)
  {
    *min = (double)imColorMin(data_type);
    *max = (double)imColorMax(data_type);
    return 1;
  }

  return iDecorrClipRange(data_type, min, max);
}

static int iDecorrCheckImage(const imImage* image)
{
  double min, max;

  return image->color_space == IM_RGB &&
         image->depth >= 3 &&
         iDecorrClipRange(image->data_type, &min, &max);
}

static int iDecorrCheckMask(const imImage* mask_image, const imImage* src_image)
{
  return (mask_image->color_space == IM_GRAY || mask_image->color_space == IM_BINARY) &&
         mask_image->data_type == IM_BYTE &&
         mask_image->width == src_image->width &&
         mask_image->height == src_image->height;
}

static int iDecorrMoments(const imImage* src_image, const imImage* mask_image, int is_lab,
                          double* mean, double* cov, double* sample_count, int counter)
{
  const imbyte* mask = mask_image? (const imbyte*)mask_image->data[0]: 0;
  double type_min, type_max;

  iDecorrRangeFor(src_image->data_type, is_lab, &type_min, &type_max);

  switch(src_image->data_type)
  {
  case IM_BYTE:
    return DoMoments((imbyte**)src_image->data, mask, src_image->width, src_image->height,
                     is_lab, type_min, type_max, mean, cov, sample_count, counter);
  case IM_SHORT:
    return DoMoments((short**)src_image->data, mask, src_image->width, src_image->height,
                     is_lab, type_min, type_max, mean, cov, sample_count, counter);
  case IM_USHORT:
    return DoMoments((imushort**)src_image->data, mask, src_image->width, src_image->height,
                     is_lab, type_min, type_max, mean, cov, sample_count, counter);
  case IM_INT:
    return DoMoments((int**)src_image->data, mask, src_image->width, src_image->height,
                     is_lab, type_min, type_max, mean, cov, sample_count, counter);
  case IM_FLOAT:
    return DoMoments((float**)src_image->data, mask, src_image->width, src_image->height,
                     is_lab, type_min, type_max, mean, cov, sample_count, counter);
  case IM_DOUBLE:
    return DoMoments((double**)src_image->data, mask, src_image->width, src_image->height,
                     is_lab, type_min, type_max, mean, cov, sample_count, counter);
  }

  return IM_PROCESS_ABORT;
}

static int iDecorrApply(const imImage* src_image, imImage* dst_image,
                        const imDecorrelationTransform* transform, int counter)
{
  double type_min, type_max;

  iDecorrRangeFor(src_image->data_type, iDecorrIsLab(transform->color_space),
                  &type_min, &type_max);

  switch(src_image->data_type)
  {
  case IM_BYTE:
    return DoApply((imbyte**)src_image->data, (imbyte**)dst_image->data,
                   src_image->width, src_image->height, transform, type_min, type_max, counter);
  case IM_SHORT:
    return DoApply((short**)src_image->data, (short**)dst_image->data,
                   src_image->width, src_image->height, transform, type_min, type_max, counter);
  case IM_USHORT:
    return DoApply((imushort**)src_image->data, (imushort**)dst_image->data,
                   src_image->width, src_image->height, transform, type_min, type_max, counter);
  case IM_INT:
    return DoApply((int**)src_image->data, (int**)dst_image->data,
                   src_image->width, src_image->height, transform, type_min, type_max, counter);
  case IM_FLOAT:
    return DoApply((float**)src_image->data, (float**)dst_image->data,
                   src_image->width, src_image->height, transform, type_min, type_max, counter);
  case IM_DOUBLE:
    return DoApply((double**)src_image->data, (double**)dst_image->data,
                   src_image->width, src_image->height, transform, type_min, type_max, counter);
  }

  return IM_PROCESS_ABORT;
}

static void iDecorrIdentity(int color_space, imDecorrelationTransform* transform)
{
  memset(transform, 0, sizeof(imDecorrelationTransform));

  transform->matrix[0] = transform->matrix[4] = transform->matrix[8] = 1.0;
  transform->color_space = color_space;
}

static int iDecorrCalc(const imImage* src_image, int color_space, double scale,
                       const double* custom_matrix, const imImage* mask_image,
                       imDecorrelationTransform* transform, int counter)
{
  double forward[9], mean[3], cov[9], sample_count = 0.0;
  int is_lab = iDecorrIsLab(color_space);

  if (!iDecorrForward(color_space, custom_matrix, forward))
  {
    iDecorrIdentity(color_space, transform);
    return IM_PROCESS_ABORT;
  }

  /* Checked here rather than where the inverse is needed, so a custom matrix
     that cannot be inverted is reported as the failure it is instead of
     quietly becoming the identity after two passes over the image. */
  {
    double inverse[9];

    assert(iMatInv3(forward, inverse));

    if (!iMatInv3(forward, inverse))
    {
      iDecorrIdentity(color_space, transform);
      return IM_PROCESS_ABORT;
    }
  }

  if (!iDecorrMoments(src_image, mask_image, is_lab, mean, cov, &sample_count, counter))
  {
    /* The counter aborted. Leave the identity behind rather than whatever was
       on the caller's stack: the Lua binding pushes the transform whether or
       not the call succeeded, so an untouched struct reaches script as a
       table of indeterminate doubles. */
    iDecorrIdentity(color_space, transform);
    return IM_PROCESS_ABORT;
  }

  if (sample_count < 2.0)
  {
    /* nothing selected, or a single pixel: no colour cloud to measure, so the
       honest answer is to leave the image alone */
    iDecorrIdentity(color_space, transform);
    return IM_PROCESS_OK;
  }

  iDecorrBuild(mean, cov, sample_count, forward, scale,
               iDecorrUseCorrelation(color_space), transform);

  transform->color_space = color_space;

  return IM_PROCESS_OK;
}


/*************************************************************************
  Public entry points.
*************************************************************************/

int imProcessDecorrelationCalcTransform(const imImage* src_image, int color_space, double scale,
                                        const double* custom_matrix, const imImage* mask_image,
                                        imDecorrelationTransform* transform)
{
  int ret, counter;

  assert(src_image);
  assert(transform);
  assert(iDecorrCheckImage(src_image));
  assert(scale > 0);
  assert(!mask_image || iDecorrCheckMask(mask_image, src_image));

  if (!src_image || !transform || !iDecorrCheckImage(src_image) || !(scale > 0) ||
      (mask_image && !iDecorrCheckMask(mask_image, src_image)))
    return 0;

  counter = imProcessCounterBegin("DecorrelationStretch");
  imCounterTotal(counter, 2*src_image->height, "Measuring...");

  ret = iDecorrCalc(src_image, color_space, scale, custom_matrix, mask_image, transform, counter);

  imProcessCounterEnd(counter);
  return ret;
}

int imProcessDecorrelationApplyTransform(const imImage* src_image, imImage* dst_image,
                                         const imDecorrelationTransform* transform)
{
  int ret, counter;

  assert(src_image);
  assert(dst_image);
  assert(transform);
  assert(iDecorrCheckImage(src_image));
  assert(imCheckSameTypeSize(src_image, dst_image));
  assert(dst_image->color_space == IM_RGB);

  if (!src_image || !dst_image || !transform ||
      !iDecorrCheckImage(src_image) || !imCheckSameTypeSize(src_image, dst_image) ||
      dst_image->color_space != IM_RGB)
    return 0;

  counter = imProcessCounterBegin("DecorrelationStretch");
  imCounterTotal(counter, src_image->height, "Stretching...");

  ret = iDecorrApply(src_image, dst_image, transform, counter);

  imProcessCounterEnd(counter);
  return ret;
}

int imProcessDecorrelationStretch(const imImage* src_image, imImage* dst_image,
                                  int color_space, double scale)
{
  imDecorrelationTransform transform;
  int ret, counter;

  assert(src_image);
  assert(dst_image);
  assert(iDecorrCheckImage(src_image));
  assert(imCheckSameTypeSize(src_image, dst_image));
  assert(dst_image->color_space == IM_RGB);
  assert(scale > 0);

  if (!src_image || !dst_image ||
      !iDecorrCheckImage(src_image) || !imCheckSameTypeSize(src_image, dst_image) ||
      dst_image->color_space != IM_RGB || !(scale > 0))
    return 0;

  /* There is nowhere to pass a matrix through this entry point, so
     IM_DECORR_CUSTOM has no meaning here and would otherwise fail in a way
     the caller would read as a counter abort. */
  assert(color_space != IM_DECORR_CUSTOM);
  if (color_space == IM_DECORR_CUSTOM)
    return 0;

  counter = imProcessCounterBegin("DecorrelationStretch");
  imCounterTotal(counter, 3*src_image->height, "Stretching...");

  ret = iDecorrCalc(src_image, color_space, scale, 0, 0, &transform, counter);
  if (ret)
    ret = iDecorrApply(src_image, dst_image, &transform, counter);

  imProcessCounterEnd(counter);
  return ret;
}
